version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracledb
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracledb:1521:ORCL
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: password

  oracledb:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_DISABLE_ASYNCH_IO: "true"
      ORACLE_PASSWORD: password
    volumes:
      - oracledb-data:/u01/app/oracle

volumes:
  oracledb-data: